server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # This line is for React Router
        try_files $uri $uri/ /index.html; 
    }

    # This block proxies API calls
    location /api/v1 {
        # "backend" will be the name of our Spring Boot service in docker-compose
        proxy_pass http://backend:8080; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}